import Head from 'next/head'
import Header from './home/Header'
// import '@fortawesome/fontawesome-svg-core/styles.css'


export default function Home() {
  return (
    <div className='bg-neutral h-screen'>
      <Head>
        <title>Code Agency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main >
      <Header />
      </main>
    </div>
  )
}
