import Head from 'next/head'
import Contact from '../components/Contact'
import Footer from '../components/Footer'
import About from './home/About'
import Header from './home/Header'
import Portfolio from './home/Portfolio'
import RecentPosts from './home/RecentPosts'
import Service from './home/Service'
import WhyChoose from './home/whyChoose'
// import '@fortawesome/fontawesome-svg-core/styles.css'


export default function Home() {
  return (
    <div className='bg-neutral'>
      <Head>
        <title>Code Agency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      <main >
        <Header />
        <About />
        <Service />
        <Contact />
        <WhyChoose />
        <Portfolio />
        <RecentPosts />
        <Footer />
      </main>
    </div>
  )
}
